# 配置文件
# 需要哪些配置看conf/config.go
##################################

# Rest服务配置
[RestServer]
Addr = "127.0.0.1:8000"

# 数据库配置
[DataSource]
Addr = "127.0.0.1:3600"
Database = "frame"
User = "root"
Password = "ZEvmL3rFpRXd6BIX"
MaxIdle = 10
MaxOpen = 100
Migrate = false

# Redis配置
[Redis]
Addr = "127.0.0.1:6379"
Password = "ZEvmL3rFpRXd6BIX"
DB = 0
